# Generated by Django 5.0.3 on 2024-04-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imgenobjeto',
            field=models.ImageField(default=None, upload_to=None, verbose_name=''),
        ),
    ]
