# Generated by Django 5.0.3 on 2024-04-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0008_alter_categoria_imgenobjeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='imgenobjeto',
        ),
        migrations.AddField(
            model_name='categoria',
            name='Imagen',
            field=models.ImageField(default='', max_length=1000, upload_to=''),
        ),
    ]
