# Generated by Django 5.0.3 on 2024-04-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0009_remove_categoria_imgenobjeto_categoria_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='Imagen',
        ),
        migrations.AddField(
            model_name='categoria',
            name='imgenobjeto',
            field=models.ImageField(default='', max_length=1000, upload_to='', verbose_name='Imagen'),
        ),
    ]
