# Generated by Django 5.0.3 on 2024-05-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0010_remove_categoria_imagen_categoria_imgenobjeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='imgenobjeto',
            field=models.ImageField(default='', max_length=1000, upload_to='', verbose_name='Imagen'),
        ),
    ]
