# Generated by Django 5.0.3 on 2024-05-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0011_objeto_imgenobjeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='unityobjeto',
            field=models.FileField(default='', max_length=10000, upload_to='', verbose_name='UnityProject'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='unityproyect',
            field=models.FileField(default='', upload_to=None, verbose_name=''),
        ),
    ]
