# Generated by Django 5.0.3 on 2024-06-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0012_objeto_unityobjeto_proyecto_unityproyect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='unityobjeto',
            field=models.FileField(default='', max_length=10000, upload_to='', verbose_name='ObjProject'),
        ),
    ]
